### ISSUE TITLE
Bug: renderer is not a constructor

### ISSUE THREAD

**Issue by rexrainbow** [phaserjs/phaser-esbuild-typescript-template#1]
After running compiling bould.js file, I got this error message : `Uncaught TypeError: renderer is not a constructor`, which is a similar bug when running in [webpack](https://discord.com/channels/244245946873937922/617014860101845033/714910292559265803)

This error message comes from 
- Phaser4.js `this.renderer = new renderer();`  (mapped from Game.js line 46)
- `renderer` class got from previous line: `const renderer = GetRenderer();`,
- `GetRenderer()` is at line 2723, in ./phaser4.js, it should be mapped from './config/SetRanderer.ts', line 10. Which use the same instance, with `SetRenderer` method
- `SetRenderer` method is invoked in `settings.forEach(setting => setting());`, phaser4.js, line 6040.

The instance in `GetRenderer()` and `SetRenderer`()` are not the same one, 
- Instance in `GetRenderer()` is in **./phaser4.js, not ./config/SetRanderer.ts**
- Instance in `SetRenderer()` is in ./config/SetRanderer.ts

Therefore `GetRenderer()` return `undefined`.

**Comment by rexrainbow** [comment]
Uh, I should `import { Game } from '@phaserjs/phaser/Game';` not `'@phaserjs/phaser'`.

**Comment by photonstorm** [comment]
This needs solving because it's going to crop up again and again. Am looking into it now. You should _not_ have to import `Game` directly. Pulling it from the index should be fine.

**Comment by photonstorm** [comment]
Ahhh of course.. when you import from `@phaserjs/phaser` it uses the single build file, but if you import from a folder it uses that entry point instead. Hmmm, buggerations. Not entirely sure how to resolve this!

**Comment by photonstorm** [comment]
Ok, it took a while, but it now works properly!

It doesn't matter if you mix imports (i.e. globally from `@phaserjs/phaser` or directly from a function) it will uses the same instance of Phaser, so no more weird errors :)

This also means it should work properly in Webpack and Parcel too.
